title: Members
subtitle: Want to join us? [Click here](~/join).

content:
  # - name:        # name (required)
  #   avatar:      # link for avatar image
  #   tags: Web    # array or string
  #   description: # markdown supported
  #   status: active | former

  - name: Alice
    # avatar:
    tags: Misc
    description: This is a description.
    status: active

  - name: Cnily03
    avatar: https://cdn.cnily.top/avatar.png?t=1
    tags: Web
    description: "1"
    link: https://vnteam.cn
    status: active

  - name: Bob
    avatar: test.jpg
    tags: Reverse
    description: This is a very long description !!! Yes, very long...
    link: https://vnteam.cn
    status: former

  - name: Man!
    # avatar:
    tags: Re
    description: Show a [link](https://vnteam.cn) here.
    status: active

  - name: NINA
    # avatar:
    tags: Misc
    description: Girls Band Cry !!!!!
    status: former
