title:
  text: :vn(title):V&N Team
  link: /
content:
  - id: home
    text: Home
    link: /
  - id: achievements
    text: Achievements
    link: /achievements
    target: _blank
  - id: members
    text: Members
    link: /members
  - id: join
    text: Join Us
    link: /join
  - id: vnctf
    text: VNCTF
    link: /vnctf
icon:
  - icon: ":github:"
    link: https://github.com/vn-sec/vn-website
